import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]
live_config_reload = true
window.opacity = 1.0
window.startup_mode = "Maximized"

[font]
size = 14

[font.bold]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold Italic"

[font.normal]
family = "JetBrains Mono Nerd Font Mono"
style = "Medium"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 15000

[shell]
program = "/usr/bin/zsh"

[window.padding]
x = 20
y = 20
